### ISSUE TITLE
Http3Transport does not have a consistent stream ID view if proxies are involved

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-webtrans/draft-ietf-webtrans-http3#10]
In -overview, we require that "The client and the server have to agree on the numbering, so it can be referenced in the application payload.".  However, if an Http3Transport session is relayed through a proxy, it is not feasible to make the stream IDs to match on client-to-proxy and proxy-to-server, so we would have to encode a separate ID inside the stream ourselves or come up with a scheme for numbering those.

**Comment by vasilvv** [comment]
Also, since Http3Transport is pooled, exposing actual stream IDs would provide information about other traffic on the same connection, which is potentially from different origin.  So using those directly would be a security issue.

**Comment by vasilvv** [comment]
I've thought about trying to make a clever mapping scheme, but the problem is, the stream IDs can get reordered across proxy hops (otherwise there would be HOLB).  So it sounds like generating and encoding our own "global" (i.e. preserved across hops) numbers would be the only way.

**Comment by ianswett** [comment]
H3 makes an effort to not expose QUIC stream IDs directly, partially for this reason, and I believe it was a good design choice.

Are we certain stream IDs need to be referenced in the application payload?  It seems a bit like a layering violation.

**Comment by vasilvv** [comment]
I seem to recall us reaching a consensus at some point that we don't actually need this; can we just close this issue?

**Comment by vasilvv** [comment]
Discussed at IETF 111.  The answer appears to be "we do not have stream IDs".
