### ISSUE TITLE
Priorities and Pooling

### ISSUE THREAD

**Issue by afrind** [ietf-wg-webtrans/draft-ietf-webtrans-http3#102]
I made this comment on a PR related to the Warp draft for moq: https://github.com/kixelated/warp-draft/pull/98

How are streams across different WebTransport sessions prioritized? The WebTransport CONNECT request can have an HTTP Priority header -- one logical interpretation is that all streams belonging to that session be prioritized "under" that top level prioritization. eg: if I have two sessions at the same urgency and incremental on, session A has 3 streams and session B has 1, then I might expect the scheduler to round-robin at the session level (rather than the QUIC stream level), splitting the bandwidth 50/50 between A and B. Is that correct?  For WebTransport over H2, that is the most natural (or only) interpretation.

**Comment by DavidSchinazi** [comment]
Let's discuss at 116. This could be a new feature in the drafts or it could be tackled by a future extension.

**Comment by LPardue** [comment]
FWIW, RFC 9218 sort of recommends sharing already for conventional CONNECT; https://www.rfc-editor.org/rfc/rfc9218.html#name-scheduling-and-the-connect-

I keep hearing that people want strict ordering guarantees among streams. Are you saying that you'd want a fair share of bandwidth but strict ordering inside that fair share?

**Comment by afrind** [comment]
> fair share of bandwidth but strict ordering inside that fair share

I think I want to apply the HTTP prioritization per WT session (so one session could entirely block another, if they have different urgency, eg) but additional ability to prioritize streams within that session, which could be strict ordering, incremental or some combination.

**Comment by afrind** [comment]
Discussed the following at IETF 116

Option 1: Nothing, you get what you get and don’t throw a fit
Option 2: Streams are prioritized globally, be careful what you pool
Option 3: WebTransport sessions are round robin, any stream prioritization is scoped within a session 
	What about HTTP request streams?
Option 4: WebTransport sessions and HTTP request streams are prioritized by Priority header, any WebTransport stream prioritization is scoped within a session

The sense I got from the room was that folks preferred Option 4.
