### ISSUE TITLE
MAX_WEBTRANSPORT_SESSIONS or WEBTRANSPORT_MAX_SESSIONS?

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-webtrans/draft-ietf-webtrans-http3#108]
The draft uses both but I presume they refer to the same thing, so lets pick one.

**Comment by ekinnear** [comment]
Ah, left over from a previous change, I believe. `WEBTRANSPORT_*` is the correct form, can update to match.

**Comment by LPardue** [comment]
Yep sgtm
