### ISSUE TITLE
Section 2: Aspects not covered in the protocol overview

### ISSUE THREAD

**Issue by aboba** [ietf-wg-webtrans/draft-ietf-webtrans-http3#111]
A discussion on the MoQ list has highlighted widely held misunderstandings about the WebTransport architecture.  Lucas Pardue provides a clarifying post here: 
https://mailarchive.ietf.org/arch/msg/moq/yOnZu3d5mDZGcV1mBODJ2-MTeko/

Since the misunderstandings that Lucas debunks are widely held (I have heard them repeated by at least 4 developers), it seems like they should be covered in Section 2.

**Comment by aboba** [comment]
Suggestion: pointer to a reference implementation to demonstrate that implementing WebTransport isn't a monumental task.

**Comment by ekinnear** [comment]
Discussed in editor's meeting: @aboba to start with Lucas's text in a PR and we can iterate during review.
