### ISSUE TITLE
What if capsule negotiation fails?

### ISSUE THREAD

**Issue by huitema** [ietf-wg-webtrans/draft-ietf-webtrans-http3#112]
Per RFC 9297: _"Endpoints indicate that the Capsule Protocol is in use on a data stream by sending a Capsule-Protocol header field with a true value."_ What happens if a client does not include the Capsule-Protocol header field in a Connect request, or if it sets the value to false? Similarly, what if the server does not include the value or set it to false?

Webtransport only uses the Capsule protocol to send the `CLOSE_WEBTRANSPORT_SESSION` capsule. If the capsule protocol is not negotiated, what are the options? Should the node just close the connect stream in case of "no error"? Should they use "reset" with an appropriate error code?

Shouldn't the behavior be specified in the draft?

**Comment by LPardue** [comment]
I agree the spec would benefit from being more explicitly here. I would suggest if an endpoint does not send the correct signal to enable the Capsule Protocol on the data stream (I.e. the request stream) then the receiver fails closed. In other words an extended CONNECT request that doesn't include `capsule-protocol: ?1` must be rejected with an error status code. And a sucessful response to an extended CONNECT request, where the response does not include the field, must cause the stream to be terminated.

**Comment by DavidSchinazi** [comment]
That wasn't the intent of the header. You can use WebTransport (and CONNECT-UDP for that matter) without setting the `capsule-protocol` header. For WebTransport, the capsule protocol is in use as soon as there's a 2xx response

**Comment by LPardue** [comment]
Wait up. So I agree the header isn't mandatory for capsule protocol. 

I think the confusion here is that the spec days the `webtransport` enables the capsule protocol but that can be overlooked. The spec could be a bit more clear what the implications of this all are. Possibly also specifically saying that the capsule-protocol is not in play.

If my updated understanding applies, you can't get into a logical mismatch as I described earlier, so my earlier suggestion is moot.

**Comment by DavidSchinazi** [comment]
Yeah maybe we just need to say explicitly that in WebTransport a 2xx response is what starts the capsule protocol.

**Comment by LPardue** [comment]
To Christian's point though, we need to make it clear tht a server that sees `:protocol: webtransport` and `capsule-protocol: ?0`* shouldn't generate an error because the header is not used.

* https://httpwg.org/http-extensions/draft-ietf-httpbis-sfbis.html#name-parsing-a-boolean

**Comment by DavidSchinazi** [comment]
SGTM
