### ISSUE TITLE
Reserved HTTP/3 error codes for Webtransport have a name, for what purpose?

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-webtrans/draft-ietf-webtrans-http3#117]
By my understanding, we are reserving a range of error codes for WebTransport applications to use. At the time of writing, the IANA considerations says to reserve these as `H3_WEBTRANSPORT_APPLICATION_<MIN>..H3_WEBTRANSPORT_APPLICATION_<MAX>` (where <MIN> and <MAX> are a little in flux due to the extension of the space in https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/115.

What isn't clear to me is who the intended audience of those error code names are? Applications on top of WebTransport are probably going to want to use their own semantic names for the errors (e.g. MOQ_NO_ERROR, MOQ_AWFUL_THING) or whatever. They could do that by saying something like 

> when condition X happens, close the WebTransport session with MOQ_AWFUL_THING ((WebTransport error code 1)|. 

Or is the intention that they will use a form like:

> > when condition X happens, close the WebTransport session with MOQ_AWFUL_THING ((H3_WEBTRANSPORT_APPLICATION_000001). 

Whatever the preference, we should probably start thinking about how to explain to people consistent sytyling for using WebTransport. So this is possibly or more general question.

**Comment by DavidSchinazi** [comment]
The IANA registry has a mandatory `Name` column, I think the audience is anyone reading that registry?

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting. No strong opinions but everyone seemed fine with switching to a single name for the whole range.
@LPardue can you write a PR?

**Comment by LPardue** [comment]
Yep by the 3nd of the week
