### ISSUE TITLE
Add guidance about the intended use of capsules

### ISSUE THREAD

**Issue by afrind** [ietf-wg-webtrans/draft-ietf-webtrans-http3#119]
Even though the CONNECT stream uses capsules and capsules are extensible, application protocols written on top of WebTransport are not intended to define their own capsules to send in this context.  The w3c API for webtrans doesn't have a mechanism for sending capsules as they are intended to be a channel for the user-agent rather than the application.  We should add some guidance to this effect.

**Comment by LPardue** [comment]
I might go as far to suggest that we RECOMMEND not doing it along with the guidance. If people need more capsules, they should extend WebTransport not via the application.

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting. Sounds reasonable, let's see a PR

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting. Plan is to not use 2119 keywords and instead write prose.
