### ISSUE TITLE
Unify on a single setting to indicate support for WebTransport?

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-webtrans/draft-ietf-webtrans-http3#125]
This came up in an editor's call when keeping settings in sync. Several folks thought this was already unified, so filing an issue to cover cleaning this up.

Today, HTTP/2 uses `SETTINGS_WEBTRANSPORT_MAX_SESSIONS` instead of `SETTINGS_ENABLE_WEBTRANSPORT` to indicate support for WebTransport and requires both the client and the server to send the setting with a non-zero value.

HTTP/3 still uses _both_ `SETTINGS_WEBTRANSPORT_MAX_SESSIONS` and `SETTINGS_ENABLE_WEBTRANSPORT`, and at the time we said it was in part due to the fact that "h3 requires `SETTINGS_ENABLE_WEBTRANSPORT` because it changes the format of server-initiated bidi streams" ([context](https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http2/issues/73#issuecomment-1464720983)).

However, we've said that `SETTINGS_WEBTRANSPORT_MAX_SESSIONS` > 0 is semantically equivalent to `SETTINGS_ENABLE_WEBTRANSPORT`.

If that's the case, then it should be okay to replace that setting with the one by a different name, with otherwise identical language. It's a little bit odd to send `SETTINGS_WEBTRANSPORT_MAX_SESSIONS` from an endpoint that isn't able to have sessions opened to it, but it seems like completely eliminating a setting reduces complexity and the actual string spelling of the setting name isn't that important. That would unify both HTTP/2 and HTTP/3 on a single way to say "yes, I speak WebTransport and you can speak WebTransport to me".

Concretely, the proposal is to replace uses of
`SETTINGS_ENABLE_WEBTRANSPORT` = 1
with
`SETTINGS_WEBTRANSPORT_MAX_SESSIONS` = 1
with no other change in meaning or semantics.

**Comment by LPardue** [comment]
This seems like a good change. 

> Concretely, the proposal is to replace uses of
> SETTINGS_ENABLE_WEBTRANSPORT = 1
> with
> SETTINGS_WEBTRANSPORT_MAX_SESSIONS = 1
> with no other change in meaning or semantics.

I think practically this substitution is more like moving to "greater than 0", to marry up with how the HTTP/2 spec does it.
