### ISSUE TITLE
Should clients wait for SETTINGS?

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-webtrans/draft-ietf-webtrans-http3#135]
HTTP syntax is extended by client-initiated bidirectional streams, which is why the settings for enabling WebTransport matter more than it would otherwise. This raises the question if we should have included a "fake" very high length for the "frame that runs to the end of the stream" so that a parser that's doing the wrong thing won't see the session ID and try to parse out that number of bytes.

The question is if that would matter? Would it help? Is it worth the cost (9 bytes per stream)?

The scenario: 
1. Client tries to do WT, thinking that the server does it, but it does not. 
2. Server sees a frame of a type that it doesn't recognize, so tries to read the length to skip that frame.
3. The length is actually the WT Session ID, so now the server reads that far through the byte stream and attempts to parse the next bytes as the beginning of an HTTP/3 frame. 
4. You now have the ability to write whatever HTTP/3 frames you want to the server, but the client has no idea what you're saying. 

- Hopefully, the client doesn't allow you to talk WT to a server that doesn't actually talk WT
- If you had a client that was either malicious or buggy, you could try to send these frames

Impact: 
- What sort of information could you get by sending custom HTTP/3 frames to the server? 
- This would be a CORS bypass in a browser
- Allows the attacker to access secrets in the dynamic table
     - If the connection is shared with other HTTP requests, that's especially concerning
     - You can put indices that will extract headers and then talk to an echo endpoint on the same server that will reflect them back to you
    - You can also use these headers, for example authorization

Ways to fix this: 
a. Send a sentinel frame (say, empty SETTINGS, 4 and 0) that means nothing ahead of the WT frames. WT servers will know and discard. Other implementations will fail and tear down the whole connection. 
b. Considered using max length in the WT frame, but the failure mode is less good (if someone tries to allocate that much memory, we have issues, plus it's not great to have things stall).
c. We should write down that client MUST wait until settings (this exists, but we should add it to security considerations)

Overall:
Don't offer a WT API that allows people to write arbitrary bytes to various streams.

**Comment by ekinnear** [comment]
Discussed in editor's meeting: 

(c) we should definitely do. 

We should discuss if we want to do (a).

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting. Consensus in (small, limited) room was to add some text saying clients MUST wait for settings and explaining why, and that's it. @vasilvv can you write a PR?

**Comment by LPardue** [comment]
adding guidance for the client sounds good

**Comment by DavidSchinazi** [comment]
Chair: discussed in the WG session at IETF 118. Consensus in the room was to have client wait for the server's SETTINGS before sending the WebTransport request.

**Comment by ekinnear** [comment]
Discussed in editor's meeting: @vasilvv to write PR adding this to security considerations.

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting. Plan is to write one PR that resolves #135, #140, #141, and #143. That PR would say:
* client MUST wait for server settings
* endpoints MUST send SETTINGS_H3_DATAGRAM (however servers that want to validate this MUST need to take into account the fact that the request might arrive before the client's SETTINGS)
* client no longer sends the WEBTRANSPORT_MAX_SESSIONS setting
* Add a "Considerations for future versions of WebTransport" section that explain that if a future version of WebTransport changes the syntax of the request, it'll need to change the Upgrade Token. Similarly, changes to stream formats will require changes to the Unidirectional Stream Type and Bidirectional Stream Signal Value.
