### ISSUE TITLE
Define a header for subprotocol negotiation

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-webtrans/draft-ietf-webtrans-http3#137]
To be able to implement w3c/webtransport#536 (see moq-wg/moq-transport#233 for some background, but the problem here is porting applications that rely on ALPN).  Client sends a list of supported subprotocols, server responds with one of the selected.

Possible syntax ideas for the client header:
- sf-list of [sf-byte-sequences](https://www.rfc-editor.org/rfc/rfc8941.html#name-byte-sequences)
- sf-list of [sf-strings](https://www.rfc-editor.org/rfc/rfc8941.html#name-strings)
- sf-list of [sf-tokens](https://www.rfc-editor.org/rfc/rfc8941.html#name-tokens)
- [RFC 7639](https://datatracker.ietf.org/doc/rfc7639/)

Possible response syntax:
- one byte-sequence/string/token
- number indicating the index of the selected subprotocol

**Comment by DavidSchinazi** [comment]
Chair: editor's meeting. Proposal is to have client send ALPN header (using format from RFC 7639) (client can send multiple ALPNs if it wants to). Server then sends a single ALPN header. This would be an optional feature.

Thoughts?

**Comment by kixelated** [comment]
I think this is good functionality, mirroring what QUIC provides.

MoQ currently does version negotiation itself. We could leverage the CONNECT request and the ALPN for version negotiation instead. Although we'll still need to do extension negotiation, so I'm not 100% certain if this is the right direction but it's still quite useful.

**Comment by enygren** [comment]
If we use ALPN we clearly need to define how these interact with the "alpn" SvcParam in SVCB/HTTPS DNS RRs and the defined behavior there.

**Comment by DavidSchinazi** [comment]
And now speaking as individual contributor: I would suggest restricting this new ALPN-like construct to [tokens](https://www.rfc-editor.org/rfc/rfc9110#name-tokens) to avoid the encoding footgun that exists in ALPN.
