### ISSUE TITLE
Feedback from IANA

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-webtrans/draft-ietf-webtrans-http3#138]
IANA has sent in the following feedback:

> Any values that have yet to be allocated (either permanently or via the RFC 7120 early allocation policy), like the values named in sections 8.2, 8.3, 8.4, 8.5 and 8.6, should be described as “1 (suggested)” and “2 (suggested)” (or similar).
>
> If you have any questions, just let us know. If you'd like to talk in person, you can find us next to the RFC Editor's table from Monday through Thursday. You can also request another review at any time by contacting us at [iana@iana.org](mailto:iana@iana.org).
>
> For more information about IANA Considerations section requirements, please see https://www.iana.org/help/protocol-registration

**Comment by ekinnear** [comment]
Discussed in editor's meeting: Tracked in #136.
