### ISSUE TITLE
putting all flow control capsules on the control stream introduces head-of-line blocking

### ISSUE THREAD

**Issue by marten-seemann** [ietf-wg-webtrans/draft-ietf-webtrans-http3#152]
The current proposal (https://datatracker.ietf.org/doc/draft-thomson-webtrans-session-limit/) for transmitting flow control messages serializes the capsules onto the WebTransport control stream. Since the control stream is a QUIC stream, this means that these messages suffer from HoL blocking in the case of packet loss.

Depending on the usage pattern of the WebTransport application, this will matter more or less.

It would be nice to figure out a solution that doesn't suffer from HoL blocking.

**Comment by DavidSchinazi** [comment]
Chair: we discussed this in the room at IETF 119. Rough consensus in room was that head of line blocking was not a critical issue in this scenario and we could ignore this for now. Current plan is to close this with no action.

**Comment by DavidSchinazi** [comment]
As chair: In the two months since this was opened, we haven't seen any new information pointing to this being a real problem. We're therefore confirming the rough consensus that the WG doesn't see this as a blocking issue. I'm therefore closing this issue.
