### ISSUE TITLE
0-RTT restrictions

### ISSUE THREAD

**Issue by marten-seemann** [ietf-wg-webtrans/draft-ietf-webtrans-http3#158]
Currently the draft says:
> However, WebTransport-related SETTINGS parameters may be retained from the previous session as described in Section 7.2.4.2 of [[HTTP3](https://ietf-wg-webtrans.github.io/draft-ietf-webtrans-http3/draft-ietf-webtrans-http3.html#HTTP3)]. If the server accepts 0-RTT, the server MUST NOT reduce the limit of maximum open WebTransport sessions from the one negotiated during the previous session; such change would be deemed incompatible, and MUST result in a H3_SETTINGS_ERROR connection error.

I'm surprised by this requirement. Since WebTransport can't be dialed in 0-RTT anyway, what's the point of saving any WebTransport-related settings when doing 0-RTT. Since we have to wait for handshake completion anyway, we might as well start from a clean slate (let the server decide what SETTINGS to use on the new connection).

**Comment by DavidSchinazi** [comment]
(speaking as individual) this is pretty standard for 0-RTT handling of settings. There's nothing preventing the client from ignoring 0-RTT settings. And the server can remember by hard-coding the value in software or configuration. I'd prefer we keep this consistent with every other settings, as this would be the first one requiring special handling. Propose to close with no action.

**Comment by ekinnear** [comment]
Unless we have other places where we say that a client MUST NOT remember a SETTING for 0-RTT, I'd be hesitant to introduce one here just because it's not useful. Saying that you can't do 0-RTT and then punish someone for using the limits that you previously expressed is good, even if in this case it's just an artifact of the mechanism that we used to communicate those limits to the client (which happens to get saved for 0-RTT).

**Comment by DavidSchinazi** [comment]
Chair: any further thoughts here? Without strong motivation, it seems like the best path forward is to keep consistency with other settings. Unless there are objections, we'll close this issue with no action.

**Comment by DavidSchinazi** [comment]
Chair: due to lack of interest, closing with no action
