### ISSUE TITLE
WebTransport-Subprotocols-Available -handling of list ordering and duplicates

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-webtrans/draft-ietf-webtrans-http3#159]
> Both WebTransport-Subprotocols-Available and WebTransport-Subprotocol are Structured Fields [[RFC8941](https://ietf-wg-webtrans.github.io/draft-ietf-webtrans-http3/draft-ietf-webtrans-http3.html#RFC8941)]. WebTransport-Subprotocols-Available is a List of Tokens, and WebTransport-Subprotocol is a Token.

A list would allow duplicate entries and could have ordering significance, we probably want some explicit statement about how to handle those.

**Comment by DavidSchinazi** [comment]
(speaking as individual) +1, a few explicit statements would help. I'd suggest we disallow repetition, and have the ordering convey the client's preference
