### ISSUE TITLE
Exporters and TLS proxies

### ISSUE THREAD

**Issue by yaroslavros** [ietf-wg-webtrans/draft-ietf-webtrans-http3#170]
Historically client-side APIs in browsers such as JavaScript and WASM never had access to TLS exporter.
As far as I know exposure of TLS exporter in WebTransport would be the first precedent for in-browser code.

A TLS proxy between client and server implemented in a form of a Secure Web Gateway, a NGFW or a generic SSE service will result in exporter difference on client and server side. Applications that rely on exporter consistency to negotiate common cryptographic context will be always broken by any TLS proxy that decrypts/re-encrypts QUIC.

In recent history there were few TLS developments that relied on end-to-end encryption. They were broken badly by TLS proxies to the extend that these standards are no longer used on public internet: HPKP (RFC7469) and Token Binding (RFC8471). Here are relevant Chromium discussions about removal of these features as they backfired: https://groups.google.com/a/chromium.org/g/blink-dev/c/he9tr7p3rZ8/ and https://groups.google.com/a/chromium.org/g/blink-dev/c/OkdLUyYmY1E/

As I mentioned on the IETF120 WebTransport meeting, I would strongly suggest not to expose TLS exporters in client API as it will lead to inconsistent user experience depending on presence of a TLS proxy. These issues will be quite hard to troubleshoot for application developers as TLS proxies are typically deployed on client side.

I believe that a better design pattern for applications that do not trust HTTP/3 security and require a common shared secret over WebTransport channel would be to run own KEM within the WebTransport or leverage HPKE.

**Comment by DavidSchinazi** [comment]
We're adding key exporters at the IETF layer in service of the W3C API. Since these concerns are about the fact that we're offering exporters (as opposed to the implementation details), this should be discussed in the corresponding W3C issue: https://github.com/w3c/webtransport/issues/411. I'm closing this issue, we can continue the discussion there
