### ISSUE TITLE
Session Establishment Race

### ISSUE THREAD

**Issue by kixelated** [ietf-wg-webtrans/draft-ietf-webtrans-http3#28]
> From the client's perspective, a WebTransport session is established when the client receives a 200 response. From the server's perspective, a session is established once it sends a 200 response. Both endpoints MUST NOT open any streams or send any datagrams on a given session before that session is established.

After the client initiates the WebTransport session by sending a CONNECT request, the server sends a 200 response and is free to create streams. This means that a server-initiated stream may arrive prior to the CONNECT response. Is the client able to infer that the session was successfully established, or does the client need to buffer this stream until it receives a proper response?

**Comment by LPardue** [comment]
Since there are no ordering guarantees across streams on the receiver side, I'd say you have to buffer until the 200 is processed.

**Comment by vasilvv** [comment]
I agree with Lucas here.  We also had a similar problem in QuicTransport (server has to buffer streams before checking the origin), and we handled it by buffering.

**Comment by vasilvv** [comment]
Discussed at IETF 110.  There were no objections to buffering (with some limits), so I think we should go ahead and add it.
