### ISSUE TITLE
Session Establishment Round Trips

### ISSUE THREAD

**Issue by kixelated** [ietf-wg-webtrans/draft-ietf-webtrans-http3#29]
For a simple application that wants to send "hello world" over a WebTransport stream, it would take a minimum of 2.5 round trips for the data to arrive on the server. This is still an improvement over WebSockets but I'm wondering if we could do better.

> From the client's perspective, a WebTransport session is established when the client receives a 200 response. From the server's perspective, a session is established once it sends a 200 response. Both endpoints MUST NOT open any streams or send any datagrams on a given session before that session is established.

If the client is able to create streams prior to receiving the CONNECT response, then it would remove a round trip. The server would need to buffer any data received on streams associated with an unknown WebTransport session. If the server responds with a non-200 status code, then these streams are discarded.

> WebTransport over HTTP/3 does not support 0-RTT.

I believe 0-RTT is disabled for WebTransport because CONNECT is not idempotent and would be subject to replay attacks. An idempotent CONNECT would remove a round trip when 0-RTT is used... although I'm not sure this is a good idea.

**Comment by afrind** [comment]
> If the client is able to create streams prior to receiving the CONNECT response, then it would remove a round trip. The server would need to buffer any data received on streams associated with an unknown WebTransport session. If the server responds with a non-200 status code, then these streams are discarded.

I think this is a reasonable optimization

**Comment by LPardue** [comment]
The client requirement is odd in comparison to MASQUE / CONNECT-UDP which says "client can risk sending datagrams before getting a 200 response, a different response means that datagrams will be discarded". 

What is the motivation for the requirement in WebTransport? If you need some kind of ordering guarantees, then stream IDs provide that.

**Comment by vasilvv** [comment]
Discussed at IETF 110.  There were no objections to buffering (with some limits), so I think we should go ahead and add it.
