### ISSUE TITLE
Section 4.4: Path MTU computation

### ISSUE THREAD

**Issue by aboba** [ietf-wg-webtrans/draft-ietf-webtrans-http3#30]
From Section 4.4: 

"TODO: Describe how the path MTU can be computed, specifically propagation across HTTP proxies."

**Comment by vasilvv** [comment]
My idea was to use headers to figure this out (ietf-wg-masque/draft-ietf-masque-h3-datagram#28).  That doesn't really work for various reasons.  I suggest we wait until MASQUE working group resolves this in something like ietf-wg-masque/draft-ietf-masque-h3-datagram#65.

**Comment by gloinul** [comment]
I would strongly recommend that you make clear what requirements you have on MTU discovery from the HTTP layer for Webtrans usage of Datagram. The ongoing discussion is if HTTP Datagram will have to implement anything more than just dropping oversized HTTP Datagram.

**Comment by vasilvv** [comment]
It appears to me that the MASQUE working group decided to not do anything special about MTU handling, meaning this basically means we have to close this with no action.

**Comment by DavidSchinazi** [comment]
@vasilvv that's not quite right - the MASQUE working group decided to not enable extensibility or MTU discovery at the HTTP Datagrams layer, instead leaving this up to individual applications / HTTP upgrade tokens. Therefore WebTransport could potentially define something at the WebTransport layer if it wished to. I'm not suggesting that this would be a good idea, just mentioning that it's possible
