### ISSUE TITLE
Specify behavior when receiving a bad session ID

### ISSUE THREAD

**Issue by afrind** [ietf-wg-webtrans/draft-ietf-webtrans-http3#32]
The H3 draft is light on error handling guidance.  There are number of cases for bad session IDs:

1. The session ID is not a client initiated bidirectional stream ID
2. The session ID refers to a stream that did not perform a WebTransport handshake
3. The session ID refers to a stream that has been closed or reset

Presumably there is no error when a DATAGRAM arrives with a bad session id -- you just drop it?

For streams, perhaps HTTP_ID_ERROR is appropriate?

Issues #28 and #29 both refer to cases where you receive a session ID that has not been created yet.  Best to keep the discussion there, but it's likely we want to allow clients/servers to buffer some of these at their own discretion rather than require an error.

**Comment by vasilvv** [comment]
For 1, I think it should be an error.

For 2, we may want to clarify that the headers should be already known at that point, but it should be an error.

For 3, I am not sure how to enforce this without running into potential race conditions, so we may want to leave those as-is.

As for the datagrams, I think h3-datagram draft should handle this.

**Comment by vasilvv** [comment]
Thinking about 2 more, I think there's also a race condition in which a data stream could be received between the stream being open and headers being processed.  I'll write up a PR for 1.

**Comment by afrind** [comment]
I think for 2, I meant the ID refers to a stream where the headers were known but it was not a CONNECT stream.

**Comment by vasilvv** [comment]
Discussed at IETF 111.  Consensus for MUST close for 1, MAY close in other scenarios.
