### ISSUE TITLE
Alignment with MASQUE/CONNECT-UDP

### ISSUE THREAD

**Issue by afrind** [ietf-wg-webtrans/draft-ietf-webtrans-http3#35]
If you ignore WebTransport streams, then the base functionality of WebTransport and CONNECT-UDP+H3 DATAGRAM is virtually identical:

1. Client sends a HTTP/3 CONNECT(-UDP) request to establish a session, with a unique identifier
2. The lifetime of that stream establishes the lifetime of the session
3. The endpoints can exchange DATAGRAMS using the session ID as the flow ID

Granted there are important differences -- CONNECT-UDP has particular semantics for the receiver, and needs mechanisms for transport level extensions.  I don't think they can be completely consolidated or factored out.

Negotiation and pooling support look different at this point -- there doesn't seem to be active discussion that a server endpoint should limit the number of open CONNECT-UDP sessions, or how they can be multiplexed with standard H3, but in WT it's more controversial.

Are there any opportunities for better alignment here?

**Comment by DavidSchinazi** [comment]
@afrind what do you mean by better alignment? In what way are CONNECT_UDP and WT3 not aligned?

**Comment by afrind** [comment]
@DavidSchinazi : Mostly around feature negotiation and pooling support.

**Comment by afrind** [comment]
The Session ID/Flow ID assignment is also different.  The MASQUE approach strikes me overkill in WT, so I'm not sure we'd want to use the same mechanism for both.

**Comment by DavidSchinazi** [comment]
Regarding pooling, I think that is completely specific to WT3. I don't see value in controlling the ability to pool CONNECT-UDP more than we have the ability to control pooling of CONNECT or even GET. Do you have a use-case for this?

Regarding feature negotiation, don't they both use HTTP headers?

**Comment by DavidSchinazi** [comment]
Regarding Session ID, since WT3 needs a Datagram Flow ID regardless, I'd suggest using that as the Session ID for simplicity.

**Comment by afrind** [comment]
@DavidSchinazi : 

re: pooling: it's just a bit strange to have the divergence between MASQUE (no need to limit pooling) and WT (must have strict limits on pooling).  Why is this?

re: feature negotiation: I was referring to different SETTINGs/negotiation strategy up front rather than the session establishment.  CONNECT+headers is fine.

re: session ID: why does WT3 need a flow-id?  It would only need one if it uses "H3 DATAGRAM" but right now it's using QUIC DATAGRAM.  I'm not sure H3 DATAGRAM brings much value to WT right now, but this is a good example of where we should either align, or perhaps document why we are not aligned.

**Comment by DavidSchinazi** [comment]
Regarding pooling, I think WT3 is diverging from all other HTTP semantics here, not just CONNECT-UDP. I don't see why CONNECT-UDP should diverge from GET because WT3 is diverging from GET.

Regarding negotiation, WT3 needs a SETTING because it changes HTTP/3 semantics (e.g., the semantics of server-initiated bidirectional streams) whereas CONNECT-UDP doesn't change HTTP/3 semantics. Note that H3-DGRAM has a SETTING because it changes the semantics of the DATAGRAM frame in h3 connections.

Regarding datagram flow ID, WT3 needs a datagram flow ID in order to support multiplexing with other h3 datagram traffic, such as CONNECT-UDP. If we want WT3 to support pooling with other HTTP/3 methods (even if that's optional and disabled by default), we'll need a datagram flow ID.

**Comment by afrind** [comment]
> Regarding datagram flow ID, WT3 needs a datagram flow ID in order to support multiplexing with other h3 datagram traffic, such as CONNECT-UDP. If we want WT3 to support pooling with other HTTP/3 methods (even if that's optional and disabled by default), we'll need a datagram flow ID.

Ah - if you want to multiplex WT with any *other* HTTP/3 traffic that uses H3 DATAGRAMs, then you could have collisions with Flow-IDs.  We should open a separate issue for this.

**Comment by vasilvv** [comment]
I think my proposal would be to just do whatever draft-ietf-h3-datagram does.  That said, we would need to add text regarding context IDs.

**Comment by afrind** [comment]
I think the alignment is getting there (both using extended CONNECT, etc), and I don't have any more specific suggestions for now, especially while MASQUE appears to still be in flux pending design team outcome.
