### ISSUE TITLE
Session layer resource management

### ISSUE THREAD

**Issue by afrind** [ietf-wg-webtrans/draft-ietf-webtrans-http3#36]
QUIC manages resources, specifically streams and flow control, at the transport layer.  Since the H3 draft allows pooling, those mechanisms may be inadequate in cases where WT sessions are multiplexed with each other or standard H3.

There are two issues open tracking some different bits of this (#22/Flow Control) and (#31/~Streams), this issue is tracking whether we need to solve that by adding functionality at the WT session layer.   #27 tracks the interpretation of GOAWAY and this could also be a session level concept.

This might look like a set of frames for granting stream and flow control credit, which would presumably be a subset of the QUIC transport credit.

Some arguments against this:

1. Endpoints that require the resource management features of the transport can disable pooling and fall back to the transport for these.
2. These problems already exist in clients that pool HTTP connections to the same server between different applications (eg: browser tabs) that are generally unaware of each other.
3. "complexity"

**Comment by DavidSchinazi** [comment]
Chair: discussed at 113, closing in favor of #22
