### ISSUE TITLE
QUIC DATAGRAM vs H3 DATAGRAM

### ISSUE THREAD

**Issue by afrind** [ietf-wg-webtrans/draft-ietf-webtrans-http3#37]
WT currently uses QUIC DATAGRAMS (eg: no Flow-Id), and does it's own demultiplexing via the session ID.  This is incompatible with multiplexing other applications that use H3 DATAGRAMs, since the Flow-ID could collide with the session ID, depending on how it is chosen.

There was some discussion of this already in a PR on victor's repo: https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/21#discussion_r520160334

**Comment by vasilvv** [comment]
We should use whatever H3 DATAGRAM draft decides in order to be able to coexist with MASQUE.  I've mostly not updated the draft because I don't think there is an exact consensus for H3 DATAGRAM on the exact approach.

**Comment by afrind** [comment]
I think MASQUE and WT have achieved parity for now
