### ISSUE TITLE
URI scheme identifying WebTransport over HTTP

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-webtrans/draft-ietf-webtrans-http3#38]
We need to pick one.  The main two options are `https:` and `wt:`.

We've discussed this separately within W3C (see w3c/webtransport#198), and the conclusion there was that it would make more sense to just use `https:` URIs.  We should discuss this at the upcoming IETF meeting.

**Comment by DavidSchinazi** [comment]
(No hats) I think using https would be the simplest option here, so I'd be inclined to go with that

**Comment by vasilvv** [comment]
Discussed at IETF 110.  Consensus in the room was for using `https:`.

**Comment by vasilvv** [comment]
Consensus confirmed on the list, the scheme in the draft is already `https`.  Closing this.
