### ISSUE TITLE
SETTINGS_ENABLE_WEBTRANSPORT from the client

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-webtrans/draft-ietf-webtrans-http3#39]
How necessary is to wait for SETTINGS_ENABLE_WEBTRANSPORT from the client?  If we are a server, and we receive a request with `:protocol` set to `webtransport`, this seems like a pretty solid indication of support.  From the current language in the draft, though, the server has to pause the processing of the request in question until the SETTINGS are there (which is really annoying to implement).

One counterpoint I can see is that we could use settings to negotiate a specific version of WebTransport over HTTP/3, and in that case we *do* need to wait for settings from both parties.

**Comment by ianswett** [comment]
I really do not like the idea of delaying the processing of requests on the server side, as it seems bug/attack prone.

Given the client has to initiate the webtransport session, and there's no guarantee the client's SETTINGs will arrive before the servers(without something like ALPS), why not only have the server send the setting?  For example, websockets in H2 only requires a setting from server to client.

**Comment by vasilvv** [comment]
One tricky thing here is that whatever we do here, it has to also work with the H3_DATAGRAM setting.

**Comment by ianswett** [comment]
I'd suggest adding some requirements like:
1) The server MUST indicate support for both WebTransport and H3 datagram, or the connection MUST be closed.
2) The server MUST assume that if the client uses protocol "webtransport", that it supports both WebTransport and H3 datagram, and sending the SETTING is optional.

**Comment by vasilvv** [comment]
Discussed at the May 2021 interim.  The agreement in the room seemed to be that this is unavoidable if we want to use SETTINGS for determining the version of WebTransport to use by the server.
