### ISSUE TITLE
What status code should lead to creation of WebTransport session?

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-webtrans/draft-ietf-webtrans-http3#42]
The spec currently explicitly requires `200`.  <https://tools.ietf.org/id/draft-ietf-quic-http-34.html#name-the-connect-method> suggests that any 2xx code should work.  Should we change the text accordingly?

**Comment by DavidSchinazi** [comment]
I'd suggest server MUST send 200 and client MUST accept any 2XX. That way future extensions can apply meaning to other 2XX codes.

**Comment by yutakahirano** [comment]
What would happen if we require client to reject 2xx other than 200?
