### ISSUE TITLE
WebTransport and 0-RTT

### ISSUE THREAD

**Issue by ddragana** [ietf-wg-webtrans/draft-ietf-webtrans-http3#45]
There is this sentence about 0-RTT:

>  WebTransport over HTTP/3 does not support 0-RTT.

I think this needs a better explanation. I expect that CONNECT requests can be sent during 0-RTT period, but WebTranpsort
streams cannot be open before response to the CONNECT requests is received.
Clients may remember that WebTransport was supported by a server and may try to negotiate sessions during 0-RTT.

**Comment by vasilvv** [comment]
The MUST NOT only applies in absence of other indications; an API flag could be such indication.  That said, I am not sure it's worth investing into designing WebTransport 0-RTT support at this point.

**Comment by ddragana** [comment]
I agree  we do not need to allow 0RTT for WebTransport.

Since WebTransport does not support 0RTT what will happen to the SETTINGS_ENABLE_WEBTRANSPORT setting when 0RTT is used on a HTTP/3 connection and in the previous session WebTransport support was negotiated? There is some explanation in the HTTP/3 draft:

> If 0-RTT data is accepted by the server, its
   SETTINGS frame MUST NOT reduce any limits or alter any values that
   might be violated by the client with its 0-RTT data.

 In the WebTransport case 0RTT data is not relevant, but there may be a small window when a client has 1RTT keys but still do not have the settings from a server.
 
We can allow the client to remember WebTransport setting or WebTransport setting needs to be negotiated in each session therefore the client must wait for the settings from the server before confirming that WebTransport is supported. I am fine with either way, but I think the WebTransport draft needs a couple of sentences to explain the behavior.

**Comment by vasilvv** [comment]
HTTP/3 draft says:

> When a 0-RTT QUIC connection is being used, the initial value of each server setting is the value used in the previous session.

This obviously only works for SETTINGS_ENABLE_WEBTRANSPORT if the server is not allowed to go from 1 to 0 while accepting 0-RTT; we should probably clarify this explicitly.
