### ISSUE TITLE
HTTP/3 Transport and Alt-Svc

### ISSUE THREAD

**Issue by wilaw** [ietf-wg-webtrans/draft-ietf-webtrans-http3#47]
Moving an issue from W3C https://github.com/w3c/webtransport/issues/78 as we felt it is better handled here at IETF. OP by @LPardue. 

> 
> During the WEBTRANS BoF at IETF Singapore 106 I made a comment at the microphone about the relationship between WebTransport over HTTP/3 and Alt-Svc. I was asked to open an issue here.
> 
> __Simple Problem__
> The following are requirements from https://tools.ietf.org/html/draft-vvv-webtransport-http3-01#section-4.1:
> 
> *  In order to indicate support for Http3Transport, both the client and
>    server MUST send an empty "http3_transport_support" transport
>    parameter.  Endpoints MUST NOT use any Http3Transport-related
>    functionality unless the parameter has been negotiated.
> 
> *  If "http3_transport_support" is negotiated, support for the QUIC
>    DATAGRAM extension MUST be negotiated.
> 
> For any given HTTP/3 connection with a value of "h3-draft" that meets the following above criteria, what happens if an Alt-Svc advert on that connection incorrectly causes a client to attempt a new connection that cannot meet the same requirements? I think marking the alternative as broken is probably good enough.
> 
> __Broader problem__
> An HTTP/3 connection that coalesces connections might trip up if some of the traffic to origin is intended to be Http3Transport and some is not. An alternative for a non-Http3Transport-using authority might cause a complete changeover to fail. 
> 
> HTTP/2 defines the 421 status code that can be used to mitigate such problems but it doesn't apply to all possible error cases (only the one where extended CONNECT fails).
> 
> I think in reality, an Http3Transport server will likely want to be smart about the Alt-Svc values it produces. 
> 
> __Broader broader problem__
> How does a client discover an Http3Transport service?
> 
> We're also talking about putting Alt-Svc in the DNS. How does a client learn of the availability of Http3Transport providing server based on its name, should it even be able to?
> 
> I wrote an I-D about a related problem in https://tools.ietf.org/html/draft-pardue-alt-svc-ext-unsupported-00.

**Comment by DavidSchinazi** [comment]
Chair: discussed at 113, consensus in room to close with no action. We can revisit this when the altsvc-bis effort makes more progress over in the HTTPBIS WG

**Comment by vasilvv** [comment]
Closing as per above.
