### ISSUE TITLE
Unidirectional stream framing

### ISSUE THREAD

**Issue by afrind** [ietf-wg-webtrans/draft-ietf-webtrans-http3#48]
WT uni streams are currently defined as

`Stream Type | Preface (Session ID) | Unframed`

This was awkward to implement, and asymmetric with how client-initiated bidi WT streams are implemented (and now server-initiated bidi -- with a frame).  

I'd like to propose we change WT uni streams to 

`Stream Type | TV Frame` 

or perhaps 

`Stream Type | Preface | TV Frame`

**Comment by martinthomson** [comment]
Not discussed at IETF 111.  I don't see the point in trying to match this up with bidi streams.  All this achieves is wasting bytes for the frame type field.

**Comment by ianswett** [comment]
I tend to think the current design is fine as well.

If you think about the first value of the unidirectional stream being a frame type, not a stream type, then I think they do conceptually align with the Bidi WT streams?

**Comment by afrind** [comment]
Paging in context...

I think my reason for suggesting this was that my parser always wants to consume the stream-type when it dispatches a unidirectional stream, but given the similarities to the other WT stream types, I wanted to use the generic frame parser after dispatch.  I made it work by not consuming the type-byte in this special case.  A side effect of defining it as `Stream Type | Frames* | TV Frame` is that one could more easily add extension frames before the TV frame in the future, at the cost of an extra byte now.

I can live with it as is too.

**Comment by vasilvv** [comment]
@afrind Should I add this to the agenda for the next meeting, or should we just leave this as-is and close this issue?

**Comment by afrind** [comment]
Given the relation to the issue just opened ^ covering a similar topic on bidi streams (eg: which frames are allowed before TV), maybe we should have a brief discussion?  I think they should behave similarly.  I have the context paged in now before the meeting.  It sounds like @martin-seeman suggested Grease frames as a possible use case, in addition to "future extensions" suggested here.  Maybe a frame for signaling the initial priority in the bidi-case is plausible? 

Grease frames may be marginal in this context (you can't send one on a QPACK stream either), and any extension needs to be enabled via SETTINGS (or capsules or headers?) anyways so said extension can change the format of WT streams.  I'll counter that the cost (1 byte per stream) is low and it's easier to bake in the flexibility from the start rather than bolt it on later.

I'll reiterate that I can live with the current scheme.

**Comment by marten-seemann** [comment]
I think that the unidirectional design (having a dedicated stream type) is the much cleaner solution. There is greasing for unidirectional stream types in HTTP/3, so I don't think we need to do anything here.
I wish we also had stream types for bidirectional streams in HTTP/3, so that ship has sailed.

**Comment by afrind** [comment]
@marten-seemann - I read your position on the other issue and assumed you wanted future extensions to be able to send frames before the WT stream became unframed.  If that's true, I don't understand why you would want that capability for bidi streams but not uni streams.

**Comment by DavidSchinazi** [comment]
At IETF 114, we discussed uni/bidi streams and there was consensus in the room to be consistent between unidirectional and bidirectional. See #71

**Comment by DavidSchinazi** [comment]
Chair: understanding is that this is closed by #96, let's keep the related discussion going on in #81 which is still open
