### ISSUE TITLE
Stale references to a transport parameter in security consideration?

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-webtrans/draft-ietf-webtrans-http3#49]
https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3-01#section-6 states

> WebTransport over HTTP/3 requires explicit opt-in through the use of
   a QUIC transport parameter; this avoids potential protocol confusion
   attacks by ensuring the HTTP/3 server explicitly supports it.

I can't tell if that is stale text or if it still true. 

There is a SETTING - SETTINGS_ENABLE_WEBTRANSPORT - for extended CONNECT. Maybe that applies instead?

**Comment by vasilvv** [comment]
Yes, it used to be a transport parameter in a very early version of this draft.
