### ISSUE TITLE
New Connection throttling

### ISSUE THREAD

**Issue by wilaw** [ietf-wg-webtrans/draft-ietf-webtrans-http3#50]
Porting https://github.com/w3c/webtransport/issues/230  originally posted to W3C WT @ricea

New connections should be throttled to avoid being a DoS vector. Maybe we will just have some language in the standard to permit and encourage throttling, and leave the details to browsers.

**Comment by DavidSchinazi** [comment]
Shouldn't the throttling be performed at the W3C layer? If throttling happens, should the W3C API let the caller know?

**Comment by LPardue** [comment]
I think this is a back-to-front way of suggesting that WebTransport include something like the guidance inhttps://datatracker.ietf.org/doc/html/rfc6455#section-4.1 (which I found [via this gDoc](https://docs.google.com/document/d/1a8sUFQsbN5uve7ziW61ATkrFr3o9A-Tiyw8ig6T3puA/edit#), linked from https://chromium.googlesource.com/chromium/src/+/refs/heads/main/net/websockets/README.md


>     If the client already has a WebSocket connection to the remote
       host (IP address) identified by /host/ and port /port/ pair, even
       if the remote host is known by another name, the client MUST wait
       until that connection has been established or for that connection
       to have failed.  There MUST be no more than one connection in a
       CONNECTING state.  If multiple connections to the same IP address
       are attempted simultaneously, the client MUST serialize them so
       that there is no more than one connection at a time running
       through the following steps.

**Comment by DavidSchinazi** [comment]
Oh thanks for finding that. I'm supportive of adding something like that.

**Comment by vasilvv** [comment]
I'm actually not sure that the specific requirement in WebSocket spec is useful, compared to just recommending throttling (or other forms of resource limits) in general.

**Comment by ricea** [comment]
The WebSocket throttling in RFC6455 requires you to implement it close to
the socket layer (in particular, after DNS lookup), which is messy in
practice. I think it may be sufficient to leave the details of the
throttling to the implementation. If we want to ensure it is interoperable,
a per-network-partitiion delay based on the number of pending and
recently-failed connections should be sufficient.

**Comment by LPardue** [comment]
So given that this is over HTTP/3, what is the anticipated throttling? Is it really just trying to tell HTTP clients to not make lots of requests? Is WebTransport sufficiently more expensive than other types of requests? I'm struggling to see language we would include here that is needed over language we have in QUIC or HTTP/3 already

**Comment by ricea** [comment]
Generally a browser will only make one HTTP/3 connection per server,
regardless of how many resources the page requests. So servers don't need
to worry about a well-behaved browser initiating large numbers of
simultaneous QUIC handshakes. However, when WebTransport connections are
not pooled, it is valid to make several at the same time. If there were no
restrictions, a badly-behaved web page could request thousands of
WebTransport connections simultaneously, DoSing the server.

**Comment by LPardue** [comment]
Thanks Adam. I think phrasing thing as a design deviation from HTTP/3's recommendation to use one connection is good idea.

**Comment by vasilvv** [comment]
From what I can read from this discussion, there isn't that much in terms of design here, and this mostly requires writing up that throttling is up to the implementation.
