### ISSUE TITLE
WEBTRANSPORT_STREAM payload length?

### ISSUE THREAD

**Issue by ydnar** [ietf-wg-webtrans/draft-ietf-webtrans-http3#53]
Hi folks! Thanks for your efforts on this project. I’m really excited about what WT will enable.

I’m working on a WT3 implementation and had a question about `WEBTRANSPORT_STREAM` frames.

Why doesn’t a `WEBTRANSPORT_STREAM` header include a payload length value following the `0x41` frame type, before the session ID? (I saw this [comment]( https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/issues/26#issuecomment-793185048) but curious for more context.)

From what I can tell, this exception forces a WT3-capable H3 server to be WT3-aware—or at least aware of H3 frames that don’t conform to the [frame layout spec](https://www.ietf.org/archive/id/draft-ietf-quic-http-34.html#name-frame-layout).

I’ve modified an existing H3 implementation to pass unknown frame types and streams to an extension. Right now, in order to accommodate `WEBTRANSPORT_STREAM` frames, a receiver has to stop parsing the frame after reading the frame type, and pass the stream to an extension that could either process or skip the unknown frame.

Given that the Session ID occupies the same place where a payload length varint would be, the frame parser could parse the second varint as a "length" and the WT3 extension could interpret it as a Session ID. Workable, but seems like a kludge.

It seems like one additional byte per bidi stream seems reasonable to align these.

Could `WEBTRANSPORT_STREAM` conform to the H3 frame layout spec with a zero-length payload, and have the payload start with the Stream ID?

**Comment by vasilvv** [comment]
> Why doesn’t a WEBTRANSPORT_STREAM header include a payload length value following the 0x41 frame type, before the session ID? (I saw this comment but curious for more context.)

Because its payload length is infinite (as in, it extends until the end of the stream).

> From what I can tell, this exception forces a WT3-capable H3 server to be WT3-aware—or at least aware of H3 frames that don’t conform to the frame layout spec.
>
> I’ve modified an existing H3 implementation to pass unknown frame types and streams to an extension. Right now, in order to accommodate WEBTRANSPORT_STREAM frames, a receiver has to stop parsing the frame after reading the frame type, and pass the stream to an extension that could either process or skip the unknown frame.

Note that this does not actually solve the issue, since even if you treat it as length 0 frame, the remainder of the stream is unframed, so a regular HTTP/3 parser would fail regardless.

All WT-over-H3 implementations already have to be WT-aware since HTTP/3 does not allow server-initiated bidirectional streams.

> Could WEBTRANSPORT_STREAM conform to the H3 frame layout spec with a zero-length payload, and have the payload start with the Stream ID?

We already [discussed this at IETF 110](https://datatracker.ietf.org/doc/minutes-110-webtrans/), and the consensus was to leave this as-is.

**Comment by ydnar** [comment]
Thanks for the reply. I dug a bit more and found this comment to be a bit of helpful additional context about un-negotiated extensions vs negotiated extensions: https://github.com/quicwg/base-drafts/issues/2396#issuecomment-459171364

Maybe the ship has sailed, but I'm wondering if H3 section 7.1 could note that negotiated extensions may vary the framing: https://www.ietf.org/archive/id/draft-ietf-quic-http-34.html#section-7.1

Thanks!

**Comment by LPardue** [comment]
> Maybe the ship has sailed, but I'm wondering if H3 section 7.1 could note that negotiated extensions may vary the framing: 

I think this is covered pretty well by https://www.ietf.org/archive/id/draft-ietf-quic-http-34.html#section-9
