### ISSUE TITLE
Remove implicit SETTINGS_ENABLE_CONNECT_PROTOCOL

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-webtrans/draft-ietf-webtrans-http3#68]
[Section 3.2](https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3-02#section-3.2) currently states:
> the SETTINGS_ENABLE_WEBTRANSPORT setting implies that an endpoint supports extended CONNECT

That is not well-defined: it relies on [RFC 8441](https://datatracker.ietf.org/doc/html/rfc8441) which only discusses HTTP/2, and the relevant changes between HTTP/2 and HTTP/3 are subtle.

Since we have [a draft for extended CONNECT for HTTP/3](https://datatracker.ietf.org/doc/draft-ietf-httpbis-h3-websockets/) that is now in the RFC Editor Queue, WebTransport needs to instead refer to that and require servers to send `SETTINGS_ENABLE_CONNECT_PROTOCOL`.

**Comment by vasilvv** [comment]
This sounds like an obvious way forward.

That said, I would personally prefer to wait until we make another breaking wire protocol change.

**Comment by DavidSchinazi** [comment]
Sounds good to me, there's no rush here - in my personal opinion we just need to get this in before WGLC

**Comment by ekinnear** [comment]
More generally, it looks like we may want to remove any implied support and just require endpoints to explicitly signal support for each "layer" of capabilities that we're relying on.

**Comment by DavidSchinazi** [comment]
Discussed at IETF 115, consensus in room to require all the relevant settings and transport parameters to be sent individually - for this issue means: require that SETTINGS_ENABLE_CONNECT_PROTOCOL be sent
