### ISSUE TITLE
Stream Limits

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-webtrans/draft-ietf-webtrans-http3#70]
Moving [this](https://github.com/ietf-wg-webtrans/draft-webtransport-http2/issues/24) to HTTP/3 since it's no longer an issue for HTTP/2:

From @martinthomson:
> This is likely shared with the HTTP/3 mapping also, but I'm here first.
>
> Web applications will want some degree of certainty about the streams they are able to access. As they also operate servers, this is probably not so bad in the client-to-server direction. The main concern for client-to-server is the potential for the connection to be used for HTTP requests that consume these limits. In the server-to-client direction clients might need to provide some number of streams that it would guarantee that a server can use for a given session.
>
> As multiple sessions are involved, this gets harder, because the web security model might prevent us from exposing information about what other origins are using a shared connection for. That said, it's not clear that there is any value in withholding this information either (see https://github.com/ietf-wg-webtrans/draft-webtransport-http2/issues/23) as the security boundary is essentially already gone once coalescing is involved.
>
> (I'm deliberately not considering isolation of state by top-level browsing context; I expect that no coalescing or connection sharing would occur for different top-level sites.)

**Comment by vasilvv** [comment]
Is this not effectively same issue as #36?

**Comment by DavidSchinazi** [comment]
Chair: discussed at 113, closing in favor of #22
