### ISSUE TITLE
Bidirectional Stream Frame Ordering Requirements

### ISSUE THREAD

**Issue by marten-seemann** [ietf-wg-webtrans/draft-ietf-webtrans-http3#71]
The draft says:
> WebTransport endpoints can initiate bidirectional streams by opening an HTTP/3 bidirectional stream and sending an HTTP/3 frame with type WEBTRANSPORT_STREAM (type=0x41).

It is unclear if it is allowed to send other frames before sending the WEBTRANSPORT_STREAM frame. I can't think of any currently defined HTTP/3 frame that would make sense to send here, but that might not be the case with future extensions. At the very least, it would be nice of grease frames could be sent.

**Comment by afrind** [comment]
#48 touches on this issue for unidirectional WT streams - eg: should they be defined as a sequence of TLV frames followed by a WT TV frame which converts the stream to unframed?

**Comment by afrind** [comment]
What is the value in sending grease frames on these streams?  Specifically to allow for future extensions that send other frames before WEBTRANSPORT_STREAM?

**Comment by vasilvv** [comment]
I can imagine sending a PRIORITY_UPDATE or something of that nature, though it's not clear to me it's worth the effort compared top just not using any frames on the stream before WEBTRANSPORT_STREAM.

**Comment by DavidSchinazi** [comment]
Chair: discussed at IETF 114, consensus in the room to
* be consistent between unidirectional and bidirectional
* require WEBTRANSPORT_STREAM to be the first frame on a bidirectional stream
* this also disallows extension frames before WEBTRANSPORT_STREAM

**Comment by LPardue** [comment]
I wasn't in the room but following up on the meeting recording, I could support this proposal. However, I don't understand how we make the WEBTRANSFORM_STREAM actually do what we describe here robustly, so I opened #81
