### ISSUE TITLE
closing streams when the session is closed

### ISSUE THREAD

**Issue by marten-seemann** [ietf-wg-webtrans/draft-ietf-webtrans-http3#72]
The draft says that all streams need to be closed when the WebTransport session is closed.

This makes me wonder:
1. Which error code to use for that? Should we mandate using the same error code that the WebTransport session was closed with?
2. Stream tracking: If it's the WebTransport implementation's responsibility to reset all the stream, this means that I need to keep another list / map of streams (outside of my QUIC stack). The interesting question is how to garbage collect closed streams from that list. It seems like the only way to do so is by introducing a callback for my QUIC stack to signal that a stream was closed / reset in both directions, so I can clean it up on the WebTransport layer.

**Comment by vasilvv** [comment]
Regarding the first issue, I was going to add a separate error code, but forgot to.  Wrote #75 to address this.

Regarding the second issue, I am not sure what the question here.  In Chromium, we keep a list of stream IDs for every WebTransport session, and call Reset() on all stream once the CONNECT stream is closed.

**Comment by DavidSchinazi** [comment]
@marten-seemann gentle ping

**Comment by marten-seemann** [comment]
#75 fixes the issue. Regarding my second point, I assume that most implementations will actually keep a second map of streams around, but that's an implementation detail that we probably don't need to address in the spec.
