### ISSUE TITLE
opening WebTransport streams before the WebTransport session is established

### ISSUE THREAD

**Issue by marten-seemann** [ietf-wg-webtrans/draft-ietf-webtrans-http3#73]
In order to save a round-trip on connection establishment, a client could optimistically open streams just after sending the CONNECT request, before it has received a reply from the server.

As both unidirectional and bidirectional streams are identified by the session ID, the server will be able to associate these streams with the WebTransport session as soon as it has processed the CONNECT request.

In case the server rejects the CONNECT request, the client should probably reset / cancel these streams. Note that this doesn't require any additional logic on the server side, as the server needs to be prepared to receive streams for sessions that it didn't establish anyway (a malicious client might open streams with arbitrary session IDs, and a server should better be prepared for that).

Currently, the spec forbids opening unidirectional streams before the session is established:
> Once established, both endpoints can open unidirectional streams.

There's no such restriction for bidirectional stream.

**Comment by vasilvv** [comment]
I believe this is a left-over from the older text of the draft.  We've agreed in #29 that both types of streams should be sent immediately, and as far as I remember, that is what the Chrome implementation does.

**Comment by marten-seemann** [comment]
> I believe this is a left-over from the older text of the draft. We've agreed in https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/issues/29 that both types of streams should be sent immediately

That's great! I'll write up a PR.

> and as far as I remember, that is what the Chrome implementation does

How does that work? I tried it out, but it seems like `transport.ready` waits for the response to the CONNECT request. This is my JS code:
```js
const transport = new WebTransport(url);
await transport.ready;
let str = await transport.createBidirectionalStream();
let wr = await str.writable.getWriter();
await wr.write((new TextEncoder()).encode("Hello world!"));
await wr.close();
```
Removing the `await transport.ready` also doesn't work, then I'm getting this error:
> Uncaught DOMException: Failed to execute 'createBidirectionalStream' on 'WebTransport': No connection.

Any hint would be highly appreciated.

**Comment by vasilvv** [comment]
Good question.  I am not sure the current API state machine allows this; when I said "what the Chrome implementation does", I meant that it supports receiving streams before it considers them confirmed (for the client, it means that streams received before HTTP 200 for the CONNECT stream are buffered instead of dropped).  We should probably figure out how to allow this on the client side, but that's a W3C issue.

**Comment by marten-seemann** [comment]
From my reading of the W3C spec this is already allowed: https://www.w3.org/TR/webtransport/#dom-webtransport-createbidirectionalstream
> Run the following steps [in parallel](https://html.spec.whatwg.org/multipage/infrastructure.html#in-parallel), but abort them whenever transport’s [[[State]]](https://www.w3.org/TR/webtransport/#webtransport-state) becomes "closed" or "failed", and instead [queue a network task](https://www.w3.org/TR/webtransport/#webtransport-queue-a-network-task) with transport to [reject](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-promise-objects) p with an [InvalidStateError](https://webidl.spec.whatwg.org/#invalidstateerror).
> 1. Wait for transport’s [[[State]]](https://www.w3.org/TR/webtransport/#webtransport-state) to be "connected".
> 2. Let internalStream be the result of [creating a bidirectional stream](https://www.w3.org/TR/webtransport/#session-create-a-bidirectional-stream) with transport’s [[[Session]]](https://www.w3.org/TR/webtransport/#webtransport-session).

So maybe this is just a bug in Chrome that it returns the `DOMException`?

**Comment by DavidSchinazi** [comment]
Sounds like we need an editorial PR to clarify that this is allowed

**Comment by marten-seemann** [comment]
#80 adds some text to clarify that opening streams as well as sending datagrams is permitted as soon as the CONNECT request has been sent out.
