### ISSUE TITLE
Stream resets can leave streams half-closed indefinitely

### ISSUE THREAD

**Issue by marten-seemann** [ietf-wg-webtrans/draft-ietf-webtrans-http3#77]
Consider the following situation:
1. A opens a bidirectional WebTransport stream to B, sends some application data, and then decides to abort data transmission (i.e. it sends a RESET_STREAM frame)
2. B receives the RESET_STREAM frame before it receives the application data, and surfaces the stream reset to the WebTransport application before it had the chance to read the Session ID. Note that there's no way around this: the STREAM frames might have been lost, and A won't retransmit them since the stream was reset.

We're now in the situation where one side of the stream is reset, but the other side of the stream is still open. Unless _someone_ explicitly closes / resets the other side of the stream, it will stay this way indefinitely.

I can see two ways forward here:
1. Require A to send a STOP_SENDING frame as well. This is a kind of sad solution, as this would be a significant deviation from the QUIC stream state machine.
2. Require B to reset streams iff it processes B's stream reset before reading the session ID. We'd have to define the error code to use for that.

**Comment by DavidSchinazi** [comment]
Chair: discussed at IETF 114, consensus in room to resolve this by adding a capsule that reliably communicates that a reset stream is associated with a WebTransport session

**Comment by marten-seemann** [comment]
> We're now in the situation where one side of the stream is reset, but the other side of the stream is still open.

Adding to this:
* B doesn't know if the stream was a WebTransport or an HTTP/3 stream
* if there are multiple WebTransport sessions running on the QUIC connection, B doesn't know which transport session the stream was associated with

It now depends on the application protocol if this is problematic or not. Some application protocols might allow the peer to respond to a stream reset, which is only possible if the stream can actually be routed to that application protocol.

**Comment by DavidSchinazi** [comment]
Chair: discussed at IETF 115, consensus in room was to solve this at the QUIC layer in the QUIC WG

**Comment by DavidSchinazi** [comment]
Chair: now that [draft-ietf-quic-reliable-stream-reset](https://datatracker.ietf.org/doc/draft-ietf-quic-reliable-stream-reset/) is almost entering QUIC WGLC, we're declaring this issue unblocked and ready for PR. The PR would add a dependency on that draft with normative text on how to use it
