### ISSUE TITLE
Indefinite-length frames are too underspecified

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-webtrans/draft-ietf-webtrans-http3#81]
I'm curious how anyone has got handling of the WEBTRANSPORT_STREAM frame working based on strict following of the specs. 

WT over H3 says:

> A client can create a bidirectional stream using a special indefinite-length HTTP/3 frame that transfers ownership of the stream to WebTransport.

H3 says in https://www.rfc-editor.org/rfc/rfc9114.html#name-frame-layout:

> All frames have the following format
> HTTP/3 Frame Format {
  Type (i),
  Length (i),
  Frame Payload (..),
}

snip

> Each frame's payload MUST contain exactly the fields identified in its description. A frame payload that contains additional bytes after the identified fields or a frame payload that terminates before the end of the identified fields MUST be treated as a [connection error](https://www.rfc-editor.org/rfc/rfc9114.html#errors) of type [H3_FRAME_ERROR](https://www.rfc-editor.org/rfc/rfc9114.html#H3_FRAME_ERROR). In particular, redundant length encodings MUST be verified to be self-consistent; see [Section 10.8](https://www.rfc-editor.org/rfc/rfc9114.html#frame-parsing).

WT over h3 says of the `WEBTRANSPORT_STREAM` frame:

> The format of the frame SHALL be the frame type, followed by the session ID, encoded as a variable-length integer, followed by the user-specified stream data ([Figure 2](https://ietf-wg-webtrans.github.io/draft-ietf-webtrans-http3/draft-ietf-webtrans-http3.html#fig-bidi-client)). The frame SHALL last until the end of the stream.

So it appears that WT is trying to omit the length field to imply an Indefinate length, but H3 doesn't allow that. I'd expect a standard H3 frame parser to read the first N bytes of the session ID and incorrectly parse that as the length. I don;t think you can special case this frame, because your breaking the H3 contract that unknown frame types have a correct length that allows them to be read and discarded.

One option (lets call it A) would be to say that `WEBTRANSPORT_STREAM` has a length field of MAX_VAL and then create a new caveat that if you're a WebTransport supporting endpoint, you don't need to create a connection error the stream if it is FIN'd before that length is reached. However, that has the unfortunate problem of consuming 8 bytes at the start of every stream.

Another option (B) might be to say that the `WEBTRANSPORT_STREAM` frame is fixed length as so:

> WEBTRANSPORT_STREAM Frame {
  Type (i) = 0x41,
  Length (i),
  Session ID (i),
}

Meaning the frame only contains the Session ID field, and the length of that frame is truly the length of Session ID - satisfying the general H3 requirements. Then after this frame, you switch into WebTransport bidi streams as we seem to be going towards on #71. However, H3 endpoints that read this frame and discard it, would then move on to parsing the subsequent bytes as frames (when the sender never intended that) and bad stuff might happen.

**Comment by vasilvv** [comment]
We already discussed this in #26.  The expectation for unknown H3 frames to have length does not apply here: WebTransport support is explicitly negotiated via SETTINGS, meaning that by the time someone sends WEBTRANSPORT_STREAM, both peers know they support it.

**Comment by LPardue** [comment]
Thanks for reminding of that.

Given the discussion on #71, if ee go that way I don't think we should bother calling this an HTTP/3 frame. For all intents and purposes it isn't. Rather, we could make it clearer that WebTransport is a semantic extension to H3 that permits client bidirectional streams to start with a special byte sequence that changes the stream purpose and meaning.

**Comment by DavidSchinazi** [comment]
It needs to be registered in the h3 frame type IANA registry to avoid conflicts though

**Comment by LPardue** [comment]
You could seek to reserve the codepoint to help prevent unintended interop problems, we already do that e.g. https://www.rfc-editor.org/rfc/rfc9114.html#section-7.2.8

> Frame types that were used in HTTP/2 where there is no corresponding HTTP/3 frame have also been reserved ([Section 11.2.1](https://www.rfc-editor.org/rfc/rfc9114.html#iana-frames)). These frame types MUST NOT be sent, and their receipt MUST be treated as a [connection error](https://www.rfc-editor.org/rfc/rfc9114.html#errors) of type [H3_FRAME_UNEXPECTED](https://www.rfc-editor.org/rfc/rfc9114.html#H3_FRAME_UNEXPECTED).

**Comment by DavidSchinazi** [comment]
At the end of the day calling this an infinite-length-frame or a non-frame-that-is-reserved-in-the-list-of-frames ends up being the same thing implementation-wise. My personal two cents is that infinite-length frame is easier to explain and reason about.

**Comment by LPardue** [comment]
I disagree. With the proposal on #71, we're making a non-frame that can't have anything before or after it. This is a very special thing that sticks out and I doubt is likely to be replicated.

So I'd like to hear what other implementers have done or would do. My implementation that reads from streams already has branches that go into frame parsing mode or not depending on the stream type. If I were to add the code, I'd model it as a different stream type that is only supported when WebTransport is enabled and it wouldn't touch my frame parsing part at all.

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting, @vasilvv thinks this is resolved by #96. @LPardue do you agree?

**Comment by LPardue** [comment]
Sorry I missed that PR as I was on holiday. I believe that #96 channels the spirit of my PR #83, and addresses the original issue here

I think the text could continue to have some editorial improvements to better highlight how much of a divergence this is for request streams, but lets track the separately.

**Comment by DavidSchinazi** [comment]
Awesome, thanks Lucas! Closing based on that comment.

For the remaining editorial bits, please file a separate issue or PR :-)
