### ISSUE TITLE
WT over HTTP/3 should require capsule support and datagram support explicitly

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-webtrans/draft-ietf-webtrans-http3#84]
Per discussion at IETF 114, we should explicitly require support for each layer of capabilities that are needed. 

There was also a discussion about whether or not we needed to require datagram support, since requiring capsules technically means that you could use a datagram capsule and implementations may exist that do not want to have datagram support at all.

Documenting some of that discussion in replies to this issue, as well.

**Comment by ekinnear** [comment]
Specific to datagrams and capsules:
- WT supported means that capsule protocol is supported, thus you must always support capsules.
- Proposal: You need to have datagrams in order to do WT over HTTP/3
- Intermediaries will need to be able to either translate for upstream or ensure that upstream can provide an equivalent feature set

More generally:
- We want to explicitly call out dependencies/prerequisites so that we don't need to teach layers about other layers. For example, WT being supported doesn't mean that the layers that implement capsules, H3 datagrams, or QUIC datagrams should have any idea about the existence of WebTransport

**Comment by ekinnear** [comment]
So we need: 
- HTTP Setting: SETTINGS_H3_DATAGRAM (0x33) with a value of 1 for HTTP datagrams
- QUIC TP: max_datagram_frame_size with a value greater than 0 for QUIC datagrams
- Capsule protocol support is implicit in the `webtransport` `:protocol` entry, as explicitly called out by RFC 9297 _or_ we can require `Capsule-Protocol: true` to be sent on every extended connect request as well.

to be added to the existing
- HTTP Setting: SETTINGS_ENABLE_WEBTRANSPORT = 1
- HTTP Setting: SETTINGS_WEBTRANSPORT_MAX_SESSIONS > 0

(although we may be removing SETTINGS_ENABLE_WEBTRANSPORT)

**Comment by DavidSchinazi** [comment]
SGTM
I think we can skip mentioning Capsule-Protocol to match CONNECT-UDP
