### ISSUE TITLE
Why is use of the Origin header field a MUST

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-webtrans/draft-ietf-webtrans-http3#92]
In draft 03 the following requirement is made

> An Origin header [[RFC6454](https://www.rfc-editor.org/rfc/rfc6454)] MUST be provided within the request.

WebTransport's closest equivalent in this regard is WebSockets, which doesn't mandate the origin header; see https://www.rfc-editor.org/rfc/rfc6455#section-1.3

This requirement makes it weird to use for user agents that have no concept of an origin model. So the MUST level seems a bit overzealous.

**Comment by huitema** [comment]
It is not just the user agent. Take for example the proposed use of [Web Transport for media over Quic](https://datatracker.ietf.org/doc/draft-lcurley-warp/). That application does not have any concept of "origin" -- indeed, there is no mention of the word "origin" in that draft.
